/*
ROS node for generating pick place server request from detected objects message and yaml script
Author: Sean Cassero
8/16/15
*/


#include <ros/ros.h>
#include <sensor_msgs/PointCloud2.h>
#include <pcl_conversions/pcl_conversions.h>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/filters/passthrough.h>
#include <pcl/ModelCoefficients.h>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/sample_consensus/method_types.h>
#include <pcl/sample_consensus/model_types.h>
#include <pcl/segmentation/sac_segmentation.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/filters/extract_indices.h>
#include <pcl/kdtree/kdtree.h>
#include <pcl/segmentation/extract_clusters.h>
#include <pr2_robot/DetectedObjectsArray.h>
#include <pcl/filters/statistical_outlier_removal.h>


class pick_place_client {

public:

  explicit pick_place_client(ros::NodeHandle nh) : m_nh(nh)  {

    // define the subscriber and publisher
    m_detectedObjectSub = m_nh.subscribe ("'/detected_objects'", 1, &pick_place_client::cloud_cb, this);
    m_collisionPub = m_nh.advertise<sensor_msgs::PointCloud2> ("/pr2/3D_map/points",1);




  }

  void get_collision_map();

private:

  ros::NodeHandle m_nh;
  ros::Subscriber m_detectedObjectSub;
  ros::Publisher m_collisionPub;

  sensor_msgs::PointCloud2 m_collision_map; // the collision map to be used with the pick place server
  sensor_msgs::PointCloud2 m_table_collision_map; // the default table collision map used to construct m_collison map w/ the detected objects message


  void cloud_cb(const pr2_robot::DetectedObjectsArray& detected_objects);

}; // end class definition


void pick_place_client::get_collision_map(){

  // rotate the robot in place and save the cloud generated by the table after outlier filtration for a rotation +/-pi/2 about z axis
  // called on node initialization and saved to the private var m_table_collision_map


}


// define callback function
void pick_place_client::cloud_cb (const pr2_robot::DetectedObjectsArray& detected_objects)
{

// loop through the detected objects array and add all clouds with labels not equal to the next object in
// the pick place yaml script


}



int main (int argc, char** argv)
{
  // Initialize ROS
  ros::init (argc, argv, "pick_place_client");
  ros::NodeHandle nh;

  // get the segmentaiton object
  pick_place_client pp_client(nh);

  while(ros::ok())
  ros::spin ();

}
